name: CI

on:
  push:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    container: qmkfm/qmk_cli

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Verify Vial UID is unique
      run: python3 util/ci_vial_verify_uid.py

    - name: Compile Vial keyboards
      run: |
        make git-submodule
        python3 util/ci_compile_vial_keyboards.py
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        if-no-files-found: error
        path: |
          ./.build/fxliang_picorne_vial.uf2
